"""Picture subjects for every card and gun. Read by tools/build_data.py to write tools/art_prompts.txt.

Rules that keep the image model from drawing lettering (it cannot take negative prompts):
- never mention text, letters, words, logos, signs, posters, labels, tickets, books, screens, clock faces or compasses
- one concrete subject, described by shape and colour, with a funny touch where it fits
"""

CARD_STYLE = ("Cartoon video game illustration: {s}. One clear subject in the center, bold chunky shapes, thick dark outlines, "
              "vibrant saturated colors, glossy highlights, soft glow, simple dark navy gradient background.")
ICON_STYLE = ("Cartoon video game item icon: {s}. Single object in side view, bold chunky shapes, thick dark outlines, "
              "vibrant saturated colors, glossy highlights, isolated on a plain pure white background.")
WIDE_STYLE = ("Cartoon video game key art: {s}. Bold chunky shapes, thick dark outlines, vibrant neon colors, "
              "dramatic lighting, night city highway.")

UI = {
    "title": "a lone gunslinger hero in goggles and a red scarf standing on a neon highway, blasting a huge stampede of cute googly-eyed jelly blob monsters rushing toward him, explosions and confetti everywhere",
    "merchant": "a friendly raccoon shopkeeper leaning out of a small yellow food truck with a striped awning, holding up a shiny toy blaster",
    "chest": "a glowing golden treasure chest bursting open with rainbow light and sparkles",
    "hero": "a confident cartoon gunslinger hero bust with aviator goggles, a red scarf and a cheeky grin",
}

WEAPONS = {
    "pistol": "a chunky lime green and orange toy-like sci-fi pistol",
    "revolver": "a gleaming silver cowboy revolver with a pink pearl grip",
    "shotgun": "a short double barrel shotgun with a wooden stock and red shells",
    "smg": "a compact black and orange submachine gun with a round drum magazine",
    "minigun": "a huge yellow six barrel rotary minigun with an ammo belt",
    "sniper": "a long thick purple sniper rifle with a big chunky scope and a bipod",
    "rocket": "a fat pink rocket launcher tube with a rocket poking out the front",
    "grenade": "a stubby green grenade launcher gun with a wide barrel and a round drum",
    "laser": "a sleek purple laser blaster with a glowing violet crystal core",
    "tesla": "a blue sci-fi pistol with copper coils and crackling lightning at the tip",
    "flame": "a flamethrower gun with a red fuel tank and a small flame at the nozzle",
    "disc": "a glowing green razor frisbee with sharp teeth around the rim",
    "boomerang": "a curved wooden boomerang painted with neon pink and yellow stripes",
    "rail": "a long blue railgun with glowing energy rails and capacitor rings",
    "bees": "a gun shaped like a striped honey beehive with a nozzle, two cute bees flying out",
    "bowling": "a stubby purple cannon loaded with a shiny black bowling ball",
    "nailgun": "a yellow construction nail gun with a silver nail strip",
    "chicken": "a orange tube launcher with a yellow rubber chicken sticking out of the barrel",
    "bubble": "a translucent toy bubble blaster gun blowing big rainbow soap bubbles",
    "pinball": "a chrome tube cannon with a spring plunger and a shiny steel pinball",
    "splitbow": "a futuristic crossbow with three glowing green bolts fanned out",
    "snow": "a little white and blue cannon firing a big snowball",
}

CARDS = {
    # ---- VOLLEY
    "double_tap": "two identical golden bullets flying side by side with speed lines",
    "twin_barrels": "one compact orange and gunmetal blaster with one grip and two clearly separate parallel cylindrical barrels stacked vertically at the front, both pointing right, each firing one right-pointing glowing projectile with its trail behind on the left",
    "eyes_back": "a cartoon hero seen from behind with a big extra googly eye on the back of his head, winking at the viewer",
    "sidearms": "a hero spreading both arms out holding pistols firing left and right",
    "burst_mode": "three bullets in a tight row leaving a gun barrel one after another",
    "echo_chamber": "a ghostly blue copy of a gun firing a split second after the real one",
    "spray_pray": "a sweaty cartoon hand spraying bullets in every direction from a gun",
    "tight_choke": "a shotgun barrel squeezed narrow with pellets flying in a tight line",
    "twelve_oclock": "a perfect ring of twelve glowing bullets bursting outward from a central spark",
    "shotgun_wedding": "a white three tier wedding cake with a shotgun leaning on it and pellets flying",
    "hydra": "a three headed dragon hydra with each head spitting a bullet",
    "bullet_hell": "a dense swirl of hundreds of colorful bullets filling the air",
    "lead_curtain": "a wall of golden bullets lined up like a curtain flying forward",
    "gatling_mood": "an excited grinning gatling gun with spinning barrels and sweat drops",
    "speed_loader": "a revolver speed loader clicking six bullets into a cylinder",
    "extended_mag": "a gun with a ridiculously long magazine stretching out of the frame",
    "drum_mag": "a round drum magazine full of golden bullets",
    "trigger_happy": "a gloved finger pulling a trigger with motion blur and sparks",
    "triple_espresso": "three shaking espresso cups with jittery motion lines and steam",
    "fan_hammer": "a hand fanning the hammer of a revolver with six bullets flying out in an arc",
    "ambidextrous": "two hands each holding a pistol, crossed in front of each other",
    "warning_shot": "one giant oversized bullet next to a tiny normal bullet",
    "spiral_galaxy": "bullets spiraling outward like the arms of a purple galaxy",
    "wobbly": "a wiggly noodle shaped bullet with a happy face",
    "confetti_cannon": "a party cannon blasting rainbow confetti and streamers",
    "compass_rose": "four bullets flying out in a cross shape from a glowing star",
    "overpressure": "a chrome gun barrel with a big round pressure gauge, steam puffing out",
    "lazy_bullets": "a sleepy bullet wearing a nightcap floating slowly through the air",
    "ammo_belt": "a long ammo belt of shiny brass bullets draped in a curve",
    "shell_shock": "an empty shell casing creating a ring shockwave as it hits the ground",
    # ---- BULLETS
    "piercing": "a bullet punching straight through three red apples in a row",
    "drill_bits": "a bullet shaped like a spinning steel drill bit with sparks",
    "rubber_bullets": "a bouncy red rubber bullet bouncing with motion arcs",
    "ricochet": "a bullet bouncing off a metal plate in a zigzag with sparks",
    "pinball_wizard": "a bearded wizard in a purple robe playing a pinball table with glowing balls",
    "heat_seekers": "a missile with a red infrared eye curving toward a target",
    "smart_rounds": "a smug bullet wearing glasses and a graduation cap",
    "return_sender": "a bullet flying back along a curved arrow path like a boomerang",
    "chonky_bullets": "a fat round chubby bullet with tiny arms flexing",
    "planet_bullets": "a bullet shaped like a ringed planet flying through space",
    "muzzle_velocity": "a bullet breaking out of a sonic boom cone with speed lines",
    "long_range": "a golden telescope pointed at a tiny distant target",
    "point_blank": "a gun barrel pressed against the nose of a surprised blob monster",
    "hollow_points": "a mushroomed hollow point bullet with a bright impact flash",
    "lucky_bullet": "a golden bullet with a green four leaf clover on it",
    "headhunter": "a red crosshair locked on the head of a cartoon blob monster",
    "assassin": "a ninja in black with a smoking pistol and a red scarf",
    "overkill": "a bullet bursting through one blob monster and hitting a second one",
    "knockback_rounds": "a red boxing glove shaped bullet punching forward",
    "scope": "a sniper scope with a glowing red crosshair lens",
    "sticky_bombs": "a little bomb covered in green goo with a lit fuse",
    "explosive_rounds": "a bullet exploding into an orange fireball on impact",
    "tracer_rounds": "a glowing red tracer bullet leaving a long bright streak",
    "snake_shot": "a green snake shaped bullet slithering through the air",
    "satellite_shot": "a tiny satellite orbiting a glowing bullet",
    "home_run": "a baseball bat smacking a blob monster into the sky",
    "accelerator": "a bullet with rocket boosters on the back and flames",
    "dumdum": "a jagged bullet surrounded by red droplets",
    "armor_piercing": "a sharp black tungsten bullet piercing a steel shield",
    "ghost_rounds": "a cute white ghost shaped bullet floating through a wall",
    # ---- CHAIN REACTION
    "splinter": "a bullet shattering into two glowing shards",
    "shrapnel": "jagged metal shrapnel pieces flying outward from a blast",
    "cluster_rounds": "one bullet splitting into a cluster of five smaller bullets",
    "fractal": "a glowing bullet splitting into smaller bullets that split again in a fractal tree",
    "razor_fragments": "razor sharp metal shards spinning through the air",
    "corpse_explosion": "a blob monster popping into a burst of green goo",
    "chain_lightning": "a blue lightning bolt chaining between three blob monsters",
    "domino_effect": "a row of red dominoes falling with small explosions",
    "popcorn": "a striped bucket of popcorn exploding with kernels flying",
    "pinata": "a colorful donkey pinata bursting with candy and gold coins",
    "cascade": "a waterfall made of glowing bullets",
    "killstreak_rockets": "three small homing rockets flying in formation",
    "thunderclap": "a dark thundercloud firing a lightning bolt down",
    "bouncy_fragments": "colorful rubbery shards bouncing off a wall",
    "seeker_fragments": "tiny glowing shards with little eyes chasing a target",
    "chain_reaction": "a chain of fiery explosions in a row",
    "meat_grinder": "a spinning circular saw blade rolling forward with sparks",
    "wall_splatter": "a bullet hitting a brick wall and splitting into two",
    "mitosis_rounds": "a glowing bullet dividing in two like a cell",
    "spark_shower": "a fountain of bright yellow sparks",
    "aftershock": "a cracked ground with a ring shockwave rippling out",
    "lightning_rod": "a metal lightning rod on top of a bomb being struck by lightning",
    "volatile_fragments": "glowing unstable red shards about to explode",
    "grim_echo": "a cute grim reaper holding a smoking pistol",
    "combo_breaker": "a giant blue shockwave ring blasting blob monsters away",
    "balloon_animals": "a twisted balloon dog made of pink balloons",
    "fireworks": "colorful fireworks exploding in the night sky",
    "bowling_pins": "white bowling pins flying in every direction after a strike",
    "static_discharge": "a crackling ball of blue static electricity",
    "supernova": "an exploding star with a blinding white and gold blast",
    # ---- ELEMENTS
    "incendiary": "a bullet wrapped in roaring orange flames",
    "cryo_rounds": "an icy blue bullet with frost crystals",
    "taser_tips": "a bullet with crackling blue electric sparks",
    "venom": "a green bullet dripping venom",
    "serrated": "a bullet with a saw-toothed serrated edge",
    "molasses": "thick brown molasses dripping slowly from a bullet",
    "hypnotic": "a big eye with a hypnotic purple spiral pupil",
    "water_balloons": "a blue water balloon bursting with a big splash",
    "hot_sauce": "a bottle of hot sauce with flames shooting out of the top",
    "deep_freeze": "a blob monster frozen solid inside a block of ice",
    "high_voltage": "a glowing blue tesla coil arcing lightning",
    "neurotoxin": "a round flask of bubbling glowing green toxin",
    "hemorrhage": "a dramatic red burst of droplets",
    "steam_engine": "a cartoon steam engine whistle blowing a huge cloud of steam",
    "overload": "a fireball crackling with purple electricity",
    "conductor": "an orchestra conductor waving a baton that shoots lightning",
    "shatter": "an ice statue of a blob monster shattering into pieces",
    "wildfire": "flames spreading across a field of dry grass",
    "plague_doctor": "a plague doctor mask with a long beak and green smoke",
    "brainwashed": "a pink brain spinning inside a washing machine with bubbles",
    "rainbow_rounds": "a bullet trailing a rainbow of fire, ice, lightning and poison",
    "napalm": "a puddle of sticky burning orange fire",
    "frost_nova": "an icy blue explosion ring with snowflakes",
    "static_field": "a dome of crackling blue electricity",
    "toxic_trail": "glowing green footprints leaving toxic puddles",
    "ice_skates": "a pair of white ice skates leaving a frosty trail",
    "thermal_shock": "fire and ice crashing into each other",
    "oil_spill": "a glossy black oil puddle with a rainbow sheen",
    "voodoo": "a voodoo doll with colorful pins",
    "frostbite": "a shivering blob monster with icicles and a blue nose",
    # ---- AUTO-WEAPONS
    "spinny_blade": "a silver saw blade orbiting a glowing center",
    "blade_storm": "a whirlwind of spinning silver blades",
    "longer_chains": "a long metal chain with a spiked ball swinging in a wide circle",
    "spin_cycle": "a washing machine spinning so fast it blurs",
    "sharpened_steel": "a sword blade gleaming on a whetstone with sparks",
    "gun_drone": "a small flying drone with a tiny gun underneath",
    "drone_swarm": "a swarm of small flying gun drones",
    "rocket_drones": "a flying drone carrying two small rockets",
    "sentry": "a little sentry turret on a tripod with a glowing blue eye",
    "mine_layer": "a round landmine with a blinking red light",
    "road_saw": "a giant circular saw blade bouncing on asphalt with sparks",
    "beehive_backpack": "a backpack shaped like a beehive with bees flying out",
    "pet_chicken": "a cute white chicken proudly sitting on an egg with a lit fuse",
    "unpaid_intern": "a nervous sweating intern in a tie holding a tiny pea shooter",
    "ghost_twin": "a hero with a translucent blue ghost copy of himself beside him",
    "halo": "a glowing golden halo with small orbiting light orbs",
    "good_boy": "a heroic golden retriever wearing a tiny red cape, running",
    "tesla_coil": "a backpack with a sparking tesla coil on top",
    "meteor_buddy": "a smiling flaming meteor falling from the sky",
    "airstrike": "a fighter jet dropping a row of bombs",
    "acme_anvils": "a heavy black anvil falling from the sky",
    "boomerang_buddy": "a wooden boomerang spinning through the air",
    "shoulder_rockets": "shoulder mounted rocket pods firing two rockets",
    "laser_eyes": "a determined face shooting red laser beams from both eyes",
    "orbit_gunners": "spinning saw blades with tiny cannons attached",
    "overclocked_drones": "a flying drone with a glowing turbo engine and flames",
    "ground_spikes": "sharp metal spikes erupting from cracked ground in a circle",
    "pocket_singularity": "a swirling black hole pulling in debris",
    "buzzsaw_halo": "a ring of red buzzsaws spinning in a circle",
    "clone_vat": "a glass vat with three identical goofy clones floating inside",
    # ---- MOVEMENT
    "fresh_sneakers": "a pair of shiny new sneakers with speed lines",
    "sprinter": "a cartoon runner sprinting with dust clouds behind",
    "double_dash": "two blue dash trails streaking side by side",
    "quick_recovery": "a silver stopwatch with motion blur",
    "long_jump": "a cartoon athlete in a huge long jump mid air",
    "dash_strike": "a hero slashing through monsters in a blur",
    "burning_rubber": "flaming tire tracks on asphalt",
    "tactical_roll": "a soldier doing a combat roll with a gun",
    "gun_kata": "a hero spinning in the air with two pistols firing in a circle",
    "matrix_dodge": "a hero bending backward as bullets fly past in slow motion",
    "counter_strike": "a sword parrying a bullet with a bright spark",
    "riposte": "a fencer lunging with a rapier and an explosion behind",
    "smoke_bomb": "a round smoke bomb releasing a grey cloud",
    "afterimage": "a glowing purple silhouette left behind by a running hero",
    "blink": "a hero vanishing in a burst of purple sparkles",
    "momentum": "a rolling boulder picking up speed with dust",
    "planted_feet": "a pair of boots stuck in a block of concrete",
    "turret_mode": "a hero standing still with guns firing in every direction",
    "shoulder_check": "a hockey player body checking a blob monster",
    "speed_demon": "a red cartoon demon with racing stripes and flames",
    "bunny_hop": "a white bunny mid hop with motion lines",
    "rollerblades": "a pair of rollerblades with flames on the wheels",
    "rocket_boots": "a pair of boots with rocket thrusters firing",
    "slipstream": "swirling blue wind trails",
    "evasive": "a hero dodging sideways with afterimages",
    "ghost_walk": "a ghostly glowing footprint",
    "ground_pound": "a superhero smashing a fist into the ground with a shockwave",
    "banana_peels": "a yellow banana peel on the ground",
    "zoomies": "a dog running in a frantic circle with dust",
    "magnet_dash": "a red horseshoe magnet pulling gold coins",
    # ---- DEFENSE
    "vitamins": "a bottle of colorful vitamin pills",
    "thick_skin": "a chunky leather armor chest piece",
    "regeneration": "a glowing green heart with healing sparkles",
    "bubble_shield": "a translucent blue bubble shield",
    "fortress": "a stone castle tower with a shield on the front",
    "vampire_teeth": "a pair of white vampire fangs",
    "second_wind": "a swirling gust of white wind with sparkles",
    "cactus_suit": "a hero wearing a green cactus costume with spikes",
    "adrenaline": "a syringe filled with glowing yellow liquid",
    "big_heart": "a giant red heart",
    "medkit_drop": "a white medkit box with a red cross",
    "last_stand": "a lone hero standing tall in a spotlight",
    "retaliation": "an angry hero firing guns in every direction",
    "spite": "an angry red face with steam coming out of its ears",
    "soul_siphon": "a glowing purple soul being sucked into a gauntlet",
    "kevlar": "a black bulletproof vest",
    "growth_spurt": "a small plant growing fast with a sparkle",
    "panic_button": "a big red push button under a glass cover",
    "tough_cookie": "a cookie wearing a tiny combat helmet",
    "cat_reflexes": "a cat leaping sideways mid dodge",
    "field_medic": "a green medic bag with a white cross",
    "blood_bank": "a glowing red blood bag",
    "cockroach": "a cheeky cockroach wearing a tiny helmet",
    "reactive_armor": "armor plates exploding outward",
    "bullet_eater": "a round monster happily chomping bullets",
    "guardian_drone": "a flying drone projecting a blue energy shield",
    "rage": "a furious red face with clenched teeth and fire",
    "heart_magnet": "a heart shaped magnet pulling small hearts",
    "meditation": "a monk meditating with a calm glowing aura",
    "glass_cannon": "a cannon made of glass with cracks",
    # ---- LOOT
    "magnet": "a red horseshoe magnet pulling in purple crystals",
    "super_magnet": "a giant glowing electromagnet",
    "four_leaf": "a bright green four leaf clover",
    "greed": "a big pile of gold coins",
    "scholar": "a black graduation cap",
    "big_brain": "a huge pink glowing brain",
    "compound_interest": "a fat piggy bank with gold coins stacking up beside it",
    "dice_bag": "a leather bag spilling colorful dice",
    "more_options": "four glowing magic orbs floating in a row",
    "coupon_book": "a pair of scissors cutting through a gold coin",
    "gold_rush": "a gold miner with a pickaxe and a gold nugget",
    "treasure_sense": "a glowing magic divining rod pointing down at a buried treasure chest",
    "goblin_whistle": "a little green goblin running with a sack of gold",
    "shard_splitter": "a purple crystal cracking into two",
    "midas_touch": "a golden hand turning a blob monster into gold",
    "piggy_bank": "a smiling pink piggy bank",
    "cashback": "gold coins flying back into an open hand",
    "loaded_dice": "two red dice with a heavy glow",
    "investment_banker": "a cartoon banker in a suit holding money bags",
    "coin_toss": "a gold coin flipping in the air",
    "jackpot": "a golden slot machine spilling a waterfall of gold coins and cherries",
    "study_buddy": "two cute owls wearing tiny graduation caps",
    "snack_break": "a big sandwich with lettuce and cheese",
    "bargain_hunter": "a shopping bag overflowing with goodies",
    "crypto_wallet": "a glowing digital gold coin with circuit lines",
    "combo_master": "a flaming fist punching with a combo streak",
    "golden_gun": "a shiny golden pistol",
    "devil_deal": "a red devil hand shaking a human hand",
    "bounty_board": "a cowboy hat with a sheriff star and a bag of gold",
    "eureka": "a glowing lightbulb exploding with sparks",
    # ---- CHAOS
    "rubber_chicken": "a yellow rubber chicken flying through the air screaming",
    "clown_car": "a tiny clown car packed with clowns honking",
    "big_head": "a blob monster with a hilariously oversized head",
    "shrunk": "a tiny hero standing next to a giant boot",
    "disco_fever": "a disco ball with blob monsters dancing below",
    "party_popper": "a party popper bursting with streamers",
    "pinata_bosses": "a giant boss monster shaped pinata",
    "allergies": "a hero sneezing so hard bullets fly out",
    "bean_burrito": "a burrito with a green gas cloud",
    "moonwalk": "a hero moonwalking with a sparkly glove",
    "bouncy_castle": "a colorful inflatable bouncy castle",
    "banana_rounds": "a bullet shaped like a banana",
    "hot_potato": "a flaming hot potato being juggled",
    "lottery_ticket": "a golden scratch-off foil with sparkles",
    "mutiny": "pirate blob monsters fighting each other",
    "shop_vac": "a vacuum cleaner sucking up monsters and coins",
    "kazoo": "a kazoo blowing a blast of musical notes",
    "barrel_delivery": "a red explosive barrel falling from the sky",
    "kaboom": "a round black cartoon bomb with a lit sparking fuse, mid explosion with a big orange burst",
    "ghost_pepper": "a red ghost pepper with flames and a spooky face",
    "coin_flip": "a gold coin spinning on its edge",
    "chaos_orb": "a swirling multicolored chaos orb",
    "uno_reverse": "two curved arrows chasing each other in a circle, red and blue",
    "not_the_bees": "an angry swarm of bees",
    "yeet": "a blob monster launched into the sky with a trail",
    "hamster_wheel": "a hamster running in a wheel with sparks",
    "falling_piano": "a grand piano falling from the sky",
    "pickpocket": "a sneaky gloved hand stealing a gold coin",
    "cursed_doll": "a creepy stitched doll with button eyes",
    "mad": "a big red nuclear button with a mushroom cloud behind it",
    # ---- MASTERY
    "shell_collector": "a pile of red shotgun shells",
    "recoil_jump": "a hero flying backward from shotgun recoil",
    "belt_fed": "an ammo belt feeding into a machine gun",
    "pre_spun": "a minigun with glowing hot spinning barrels",
    "hawkeye": "a sharp hawk eye with a glowing iris",
    "wallbanger": "a bullet bouncing off a brick wall",
    "cluster_warheads": "a rocket splitting into small bomblets",
    "nuke_tips": "a tiny nuke warhead with a radiation glow",
    "sticky_grenades": "a grenade covered in green slime",
    "prism": "a prism splitting a laser into a rainbow of beams",
    "storm_caller": "a wizard summoning lightning from a storm cloud",
    "dragon_breath": "a dragon breathing a huge stream of fire",
    "extra_discs": "a stack of glowing razor frisbees",
    "big_boomer": "an enormous wooden boomerang",
    "overcharge": "an overcharged glowing battery with lightning",
    "killer_bees": "a mean bee wearing a tiny helmet and holding a stinger like a spear",
    "strike": "bowling pins exploding as a bowling ball smashes through",
    "staple_gun": "a giant stapler shooting staples",
    "chicken_coop": "a wooden chicken coop with chickens poking out",
    "bubble_bath": "a bathtub overflowing with bubbles",
    "multiball": "several shiny steel pinballs bouncing",
    "hydra_bolts": "a crossbow bolt splitting into three heads",
    "avalanche": "a huge avalanche of snow rolling down",
    "dead_eye": "a cowboy with one glowing red eye",
    "akimbo": "two pistols crossed in an X",
    "infinite_ammo": "a loop of bullets forming an infinity shape",
    "arsenal": "three guns hanging on a weapon rack",
    "overclocked": "a computer chip glowing hot with flames",
    "god_gamer": "a gamer with a glowing headset and focused eyes",
    "weapon_master": "a weapon rack full of shiny guns with a golden medal",
}
