"""Concrete single-scene prompts for local Crowd Rush card generation.

Each scene describes the gameplay effect, not the card's joke name.
"""

SCENES = {
    "twin_barrels": "One compact orange and gunmetal sci-fi blaster has one grip and TWO separate visible barrel tubes stacked one above the other at the front. Both tubes point RIGHT. Each barrel fires exactly one cyan-tipped orange bullet RIGHT; both bullet tips point right and both short motion trails remain to their LEFT. Show both barrels and both parallel bullets in the same close-up side view.",
    "spark_shower": "A critical bullet hits a green jelly blob at center. Four orange sparks radiate outward from the impact at north, south, east and west. The bullet points right, its trail behind on the left.",
    "fireworks": "A defeated jelly blob on the ground emits one rising firework from its body. It bursts overhead into ten colorful sparks in a circle. The enemy is the source of the firework.",
    "conductor": "One wet blue jelly blob is struck by bright blue lightning at center. The bolt branches from that blob to three other wet jelly blobs nearby, connecting all four with electric arcs. Water droplets on each blob.",
    "plague_doctor": "A poisoned purple jelly blob has collapsed at center. A thick luminous green poison cloud rises directly from its body and spreads toward two living jelly blobs nearby.",
    "frost_nova": "A red-scarfed cowboy is hit by one enemy projectile at center. A circular icy shockwave spreads from the cowboy, freezing nearby jelly blobs into blue frosted statues.",
    "static_field": "A red-scarfed cowboy stands at center as two separate blue electric arcs leap automatically from a small glowing field around him to two nearby jelly blobs.",
    "toxic_trail": "A red-scarfed cowboy runs to the right. Several separate vivid green poison puddles remain behind his boots on the left, while chasing jelly blobs step into them.",
    "oil_spill": "A red-scarfed cowboy dashes right, spilling a long glossy black oil puddle behind. A small orange flame touches the oil at the far left and spreads into a large blaze.",
    "spinny_blade": "One sharp cyan sawblade circles a red-scarfed cowboy on a visible curved orbit, striking one nearby jelly blob at the blade's edge.",
    "blade_storm": "Three sharp cyan sawblades circle a red-scarfed cowboy at equal spacing, each striking a different nearby jelly blob.",
    "spin_cycle": "One cyan sawblade races around a red-scarfed cowboy on a circular orbit, with multiple curved motion streaks showing a fast spin.",
    "drone_swarm": "Two small orange-and-cyan flying drones hover beside a red-scarfed cowboy, each aiming at a different jelly blob.",
    "road_saw": "One spinning circular sawblade ricochets off the road edge toward a jelly blob, leaving a sharp zigzag motion trail behind it.",
    "halo": "One glowing cyan orb circles a red-scarfed cowboy and intercepts a red enemy bullet before it reaches him; the bullet shatters on the orb.",
    "boomerang_buddy": "A curved orange boomerang flies from a red-scarfed cowboy toward a jelly blob, with an arcing return path shown behind it.",
    "shoulder_rockets": "Two small rockets launch from twin shoulder pods on a red-scarfed cowboy, each curving toward a different jelly blob with smoke trails behind.",
    "buzzsaw_halo": "Two cyan sawblades orbit a red-scarfed cowboy, cutting nearby jelly blobs; a red bleed droplet falls from one struck blob.",
    "clone_vat": "A red-scarfed cowboy fights beside two smaller matching helper cowboys, all three aiming forward at jelly blobs.",
    "dash_strike": "A red-scarfed cowboy dashes through one jelly blob from left to right, leaving a cyan speed trail; the blob bursts at the contact point.",
    "burning_rubber": "A red-scarfed cowboy dashes right with a cyan speed trail and leaves a continuous orange fire trail on the road behind him.",
    "gun_kata": "A red-scarfed cowboy dashes at center while a circular ring of outward-pointing bullets fires in all directions around him, trails on the inner side.",
    "matrix_dodge": "A red-scarfed cowboy narrowly sidesteps a red bullet in slow motion; the bullet passes beside his shoulder with a warped cyan time ripple.",
    "counter_strike": "A red-scarfed cowboy dodges a red enemy bullet and immediately fires three separate outward volleys at nearby jelly blobs.",
    "riposte": "A red-scarfed cowboy dodges a red enemy bullet; a bright orange explosion expands from his position into nearby jelly blobs.",
    "smoke_bomb": "A red-scarfed cowboy dashes right and leaves one dense grey smoke cloud behind; jelly blobs inside the cloud move sluggishly.",
    "afterimage": "A red-scarfed cowboy dashes right, leaving a translucent decoy of himself behind; jelly blobs crowd around the decoy as it begins to glow orange before exploding.",
    "momentum": "A red-scarfed cowboy runs fast to the right and fires a powerful bullet in the same direction, bright speed streaks emphasizing movement.",
    "planted_feet": "A red-scarfed cowboy stands firmly with both boots planted on the road and fires one exceptionally powerful shot at a jelly blob ahead.",
    "turret_mode": "A stationary red-scarfed cowboy stands at center like a turret, firing a neat circular ring of outward-pointing bullets toward surrounding jelly blobs.",
    "shoulder_check": "A red-scarfed cowboy dashes shoulder-first into a jelly blob, knocking it far to the right with a broad speed trail.",
    "bunny_hop": "A jelly blob bursts into a cyan dash-charge pickup that flies into a red-scarfed cowboy's boot, reigniting a bright cyan dash trail.",
    "rocket_boots": "A red-scarfed cowboy dashes right on rocket-powered boots while two small rockets launch toward jelly blobs ahead, smoke trailing left.",
    "slipstream": "A red-scarfed cowboy finishes a cyan dash and immediately fires a rapid stream of closely spaced bullets at one jelly blob ahead.",
    "evasive": "A red-scarfed cowboy twists clear of an incoming red bullet by a narrow margin, leaving a translucent cyan dodge silhouette behind him.",
    "ghost_walk": "After being hit, a red-scarfed cowboy glows translucent cyan inside a protective aura and dashes away from a second red enemy bullet.",
    "magnet_dash": "A red-scarfed cowboy dashes right while blue experience gems and gold coins curve inward from both sides toward him.",
    "vitamins": "A red-scarfed cowboy holds a bright orange vitamin bottle beside a large glowing red heart, showing new vitality.",
    "thick_skin": "A red-scarfed cowboy's thick protective armor absorbs a small red enemy bullet with a harmless spark at the armor plate.",
    "regeneration": "A wounded red-scarfed cowboy slowly heals as tiny green light motes flow into a red heart glow at his chest.",
    "bubble_shield": "One large translucent cyan bubble shield surrounds a red-scarfed cowboy and blocks a red enemy bullet on contact.",
    "fortress": "Two nested cyan shield bubbles and sturdy armor plates protect a red-scarfed cowboy from several red enemy bullets.",
    "second_wind": "A red-scarfed cowboy rises from the ground after a near defeat as a bright green heart-shaped healing glow restores him.",
    "adrenaline": "A low-health red-scarfed cowboy with a torn scarf fires an unusually powerful glowing shot at a jelly blob, red energy pulsing around him.",
    "big_heart": "A red-scarfed cowboy carries an oversized glowing red heart aura, looking sturdy but moving with heavy slow steps.",
    "last_stand": "A battered red-scarfed cowboy with little health gains a fresh cyan shield bubble while surrounded by jelly blobs.",
    "kevlar": "A red-scarfed cowboy wears a thick dark vest; a red enemy bullet dents the vest harmlessly while a heart glows beneath it.",
    "growth_spurt": "A red-scarfed cowboy reaches a new level in a burst of golden light and a red heart-shaped healing glow flows into him.",
    "reactive_armor": "A red enemy bullet strikes a red-scarfed cowboy's armor and sharp cyan fragments burst outward in a radial ring toward surrounding blobs.",
    "snack_break": "A blue experience gem drops beside a tiny red heart pickup; both fly into a red-scarfed cowboy and heal him.",
    "eureka": "A red-scarfed cowboy rises in a golden level-up glow while a dense circular ring of outward-pointing bullets bursts from him.",
    "rubber_chicken": "A defeated jelly blob launches one yellow rubber chicken projectile. The chicken bounces between two living blobs and explodes on the last hit.",
    "clown_car": "A tiny colorful clown car drives across the road from left to right, flattening jelly blobs in its path.",
    "big_head": "Several jelly blobs have comically oversized heads, one head marked by a bright critical-hit spark from a bullet.",
    "disco_fever": "A sparkling disco ball hangs above stunned jelly blobs; colored light spots make the blobs dance in place.",
    "party_popper": "A red-scarfed cowboy dashes right and a burst of colorful sharp confetti explodes from the dash path into nearby jelly blobs.",
    "pinata_bosses": "A large crowned jelly boss is struck by a bullet and gold coins pop out of its body into the air.",
    "allergies": "A red-scarfed cowboy sneezes at center and a circular ring of outward-pointing bullets bursts around him toward jelly blobs.",
    "bean_burrito": "A red-scarfed cowboy dashes away while a green poison cloud expands from the road behind him, slowing pursuing blobs.",
    "moonwalk": "A red-scarfed cowboy moves right while two separate bullets fire backward to the left from behind him, striking chasing blobs.",
    "bouncy_castle": "One jelly blob is knocked hard into the road wall and rebounds toward a second blob; a glowing zigzag motion path marks the bounce.",
    "banana_rounds": "A bullet strikes a jelly blob and a yellow banana peel drops directly beneath it onto the road.",
    "hot_potato": "One glowing hot potato ricochets among four jelly blobs in a zigzag path, then begins an orange explosion at the final blob.",
    "lottery_ticket": "A red-scarfed cowboy levels up in golden light and a closed golden treasure chest appears beside him as a lucky reward.",
    "mutiny": "One jelly blob struck by a pink charm spark turns friendly and attacks a different enemy blob beside it.",
    "shop_vac": "A dark cyan vortex on the road pulls several jelly blobs and scattered blue experience gems inward toward one center.",
    "kazoo": "A red-scarfed cowboy reloads a gun while blowing a tiny yellow kazoo; musical sound waves stun two nearby jelly blobs.",
    "barrel_delivery": "One red explosive barrel drops from above onto the road ahead of a red-scarfed cowboy, about to hit nearby jelly blobs.",
    "kaboom": "A defeated jelly blob erupts into a large orange explosion that reaches two other living jelly blobs nearby.",
    "ghost_pepper": "A red enemy bullet hits a red-scarfed cowboy; a circular burst of orange fire spews outward from him into nearby jelly blobs.",
    "coin_flip": "One gold coin spins in the air above a red-scarfed cowboy, one face glowing gold with power and the other dull red with weakness.",
    "chaos_orb": "One glowing orb floats beside a red-scarfed cowboy's gun and releases three different colored effects toward jelly blobs: fire, lightning, and ice.",
    "uno_reverse": "A red enemy bullet flies toward a red-scarfed cowboy, strikes a cyan reflection shield, and flies back toward the enemy that fired it.",
    "not_the_bees": "A bullet hits a jelly blob and two angry striped bees emerge from the impact, flying toward other blobs.",
    "yeet": "One jelly blob is hit by a strong shot from the left and flies far to the right with an exaggerated speed trail.",
    "hamster_wheel": "A red-scarfed cowboy runs along the road and a circular ring of outward-pointing bullets bursts around him toward surrounding blobs.",
    "falling_piano": "A heavy black grand piano falls straight down from above onto the largest jelly blob, flattening it.",
    "pickpocket": "A bullet hits a jelly blob from the left and one shiny gold coin pops out of the enemy at the impact point.",
    "cursed_doll": "A sinister small stitched doll glows with dark red power beside a red-scarfed cowboy while jelly blobs rush faster toward him.",
    "mad": "A nearly defeated red-scarfed cowboy revives at center in a huge white-orange blast that clears all surrounding jelly blobs.",
    "shell_collector": "A double-barrel shotgun fires a fan of many orange pellets to the right, with three extra pellets clearly joining the spread.",
    "recoil_jump": "A shotgun fires a powerful blast right while the red-scarfed cowboy holding it is kicked backward left and cyan fragments spray behind him.",
    "belt_fed": "A compact orange machine gun has an oversized drum magazine and a long belt of ammunition feeding a rapid stream of bullets to the right.",
    "pre_spun": "A large six-barrel orange minigun already spins at full speed before firing, with curved rotation streaks around the barrels.",
    "hawkeye": "A long scoped rifle fires one right-pointing bullet that passes cleanly through several jelly blobs in a straight line.",
    "wallbanger": "One right-pointing bullet hits the road wall, rebounds toward a jelly blob, then rebounds again along a clear zigzag path.",
    "cluster_warheads": "One orange rocket flies right and splits into four smaller right-pointing bomblets spreading toward four jelly blobs, smoke trails behind every projectile.",
    "nuke_tips": "One rocket strikes a jelly blob and produces an unusually wide orange blast circle reaching several distant blobs.",
    "sticky_grenades": "One round grenade sticks visibly to a jelly blob's body, fuse glowing, while the blob looks alarmed.",
    "prism": "One purple beam gun emits three parallel bright violet beams to the right toward jelly blobs.",
    "storm_caller": "One blue electric bolt strikes a jelly blob then chains through four nearby blobs in sequence, connected by visible lightning arcs.",
    "dragon_breath": "A flamethrower points right with a long orange flame stream that ignites a broad fire patch on the road beneath jelly blobs.",
    "extra_discs": "Three separate round cyan throwing discs fly side by side to the right toward jelly blobs, each disc visibly circular.",
    "big_boomer": "One oversized curved wooden boomerang flies right through a jelly blob and arcs back along a curved return trail.",
    "overcharge": "A long orange railgun builds a bright cyan charge between two rails before firing one exceptionally powerful right-pointing bolt.",
    "killer_bees": "Five angry striped bees emerge from a beehive launcher and swarm one jelly blob, stinging it.",
    "strike": "A cannon launches two large glossy black bowling balls to the right, rolling toward jelly blobs.",
    "staple_gun": "A yellow nail gun shoots a silver nail to the right, pinning one jelly blob against the road wall.",
    "chicken_coop": "An orange launcher fires three yellow rubber chickens to the right in a fan toward jelly blobs.",
    "bubble_bath": "One oversized translucent soap bubble encloses three jelly blobs together, lifting them from the road.",
    "multiball": "One shiny steel pinball hits the road wall and rebounds as two separate pinballs moving in different directions.",
    "hydra_bolts": "A crossbow fires one arrow to the right; it splits into three cyan bolts that curve toward three separate jelly blobs.",
    "avalanche": "A large white snowball rolls to the right, grows much bigger, and freezes a jelly blob blue on contact.",
    "dead_eye": "A scoped revolver fires one critical right-pointing bullet that pierces straight through several jelly blobs, leaving a bright impact spark at each.",
    "akimbo": "A red-scarfed cowboy holds two compact orange guns and fires two right-pointing bullets at one jelly blob, with spent magazines nearby.",
    "infinite_ammo": "An orange gun fires a continuous stream of right-pointing bullets, fed by a glowing endless cyan ammunition loop instead of a magazine.",
    "arsenal": "A red-scarfed cowboy fires three distinct orange weapons at once, all pointing right toward jelly blobs.",
    "overclocked": "A red-scarfed cowboy fires a much faster stream of bullets from a glowing hot orange gun while a red enemy bullet threatens him.",
    "god_gamer": "A red-scarfed cowboy dodges a red enemy bullet by inches and fires a critical glowing right-pointing shot into a jelly blob.",
    "weapon_master": "Three different orange guns float around a red-scarfed cowboy, each glowing brighter and firing stronger shots toward jelly blobs.",
}
